version: '2.3'
services:
  jenkins:
    build: jenkins
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - GITHUB_USER=${GITHUB_USER}
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_PASS=${DOCKER_PASS}

    ports:
      - 8080:8080
      - 55888:55888
networks:
    default:
        external:
            name: xebialabs-compose_default
