version: '3'
services:
  xl-deploy:
    image: xebialabs/xl-jetpack-deploy:8.6.1
    container_name: xld
    ports:
    - "4516:4516"
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
  xl-release:
    image: xebialabs/xl-jetpack-release:8.6.1
    container_name: xlr
    ports:
    - "5516:5516"
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y